# Generated by Django 4.2.26 on 2026-04-03 09:32

import auth_app.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP Address')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username_tried', models.CharField(blank=True, max_length=255, verbose_name='Username Tried')),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'db_table': 'login_attempt',
                'indexes': [models.Index(fields=['ip_address', 'attempted_at'], name='login_attem_ip_addr_b37527_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaptchaChallenge',
            fields=[
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('captcha_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='CAPTCHA ID')),
                ('captcha_text', models.CharField(default=auth_app.models._generate_captcha_text, max_length=10, verbose_name='CAPTCHA Text')),
                ('expires_at', models.DateTimeField(db_index=True, default=auth_app.models._captcha_expiry, verbose_name='Expires At')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Is Used')),
                ('requested_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Requested By IP')),
            ],
            options={
                'verbose_name': 'CAPTCHA Challenge',
                'verbose_name_plural': 'CAPTCHA Challenges',
                'db_table': 'captcha_challenge',
                'indexes': [models.Index(fields=['expires_at', 'is_used'], name='captcha_cha_expires_869111_idx')],
            },
        ),
    ]
