# Generated by Django 4.2.26 on 2026-09-08 07:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('title', models.CharField(max_length=200, verbose_name='Banner Title / Alt Text')),
                ('image', models.ImageField(upload_to='banners/frontpage/%Y/%m/', verbose_name='Banner Image')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Is Featured (Visible on Slideshow)')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Display Order')),
                ('click_url', models.URLField(blank=True, null=True, verbose_name='Click URL (Optional Destination)')),
            ],
            options={
                'verbose_name': 'Front Page Banner',
                'verbose_name_plural': 'Front Page Banners',
                'db_table': 'front_page_banner',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
