# Generated by Django 4.2.26 on 2026-04-01 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Auto-generated from title. Never change after publishing.', max_length=280, unique=True, verbose_name='URL Slug')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blogs/covers/%Y/%m/', verbose_name='Cover Image')),
                ('meta_description', models.CharField(blank=True, help_text='Used for search engine snippets. Max 160 characters.', max_length=160, verbose_name='Meta Description')),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=1, verbose_name='Estimated Read Time (minutes)')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Is Published')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Published At')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'db_table': 'blog',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('type', models.CharField(choices=[('text', 'Text / Markdown'), ('image', 'Image'), ('video', 'Video Embed'), ('quote', 'Pull Quote'), ('code', 'Code Snippet')], db_index=True, max_length=10, verbose_name='Block Type')),
                ('order', models.PositiveIntegerField(verbose_name='Display Order')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/blocks/%Y/%m/', verbose_name='Block Image')),
                ('meta', models.JSONField(blank=True, null=True, verbose_name='Block Meta (JSON)')),
            ],
            options={
                'verbose_name': 'Blog Block',
                'verbose_name_plural': 'Blog Blocks',
                'db_table': 'blog_block',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Guest Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Guest Email')),
                ('content', models.TextField(verbose_name='Comment Content')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP Address')),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Only approved comments are shown publicly.', verbose_name='Is Approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'db_table': 'blog_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], db_index=True, max_length=10, verbose_name='Reaction Type')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP Address')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blog.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name': 'Blog Reaction',
                'verbose_name_plural': 'Blog Reactions',
                'db_table': 'blog_reaction',
            },
        ),
    ]
