# Generated by Django 4.2.26 on 2026-04-01 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogreaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_reactions', to=settings.AUTH_USER_MODEL, verbose_name='User (if authenticated)'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog', verbose_name='Blog'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcomment', verbose_name='Parent Comment'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='User (if authenticated)'),
        ),
        migrations.AddField(
            model_name='blogblock',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blog.blog', verbose_name='Blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddIndex(
            model_name='blogreaction',
            index=models.Index(fields=['blog', 'reaction_type'], name='blog_reacti_blog_id_55542e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogreaction',
            index=models.Index(fields=['blog', 'ip_address'], name='blog_reacti_blog_id_c080d0_idx'),
        ),
        migrations.AddIndex(
            model_name='blogreaction',
            index=models.Index(fields=['user'], name='blog_reacti_user_id_01f531_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blogreaction',
            unique_together={('blog', 'user')},
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['blog', 'is_approved'], name='blog_commen_blog_id_9a45f3_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['blog', 'parent'], name='blog_commen_blog_id_976623_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['parent'], name='blog_commen_parent__43ce68_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['user'], name='blog_commen_user_id_dd6a39_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['ip_address'], name='blog_commen_ip_addr_760826_idx'),
        ),
        migrations.AddIndex(
            model_name='blogblock',
            index=models.Index(fields=['blog', 'order'], name='blog_block_blog_id_32b34d_idx'),
        ),
        migrations.AddIndex(
            model_name='blogblock',
            index=models.Index(fields=['type'], name='blog_block_type_095025_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blogblock',
            unique_together={('blog', 'order')},
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='blog_slug_3dda8b_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['author'], name='blog_author__80afb8_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['is_published', 'published_at'], name='blog_is_publ_028b0d_idx'),
        ),
    ]
