# Generated by Django 4.2.26 on 2026-05-05 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogblock',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='blogreaction',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='blogcomment',
            name='blog_commen_ip_addr_760826_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogreaction',
            name='blog_reacti_blog_id_c080d0_idx',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='name',
        ),
        migrations.AddField(
            model_name='blog',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Guest Author Name'),
        ),
        migrations.AlterField(
            model_name='blogblock',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='blogblock',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/blocks/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='blogblock',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogblock',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='blogblock',
            name='type',
            field=models.CharField(choices=[('text', 'Text / Markdown'), ('image', 'Image'), ('video', 'Video Embed'), ('quote', 'Pull Quote'), ('code', 'Code Snippet')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcomment'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogreaction',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='blogreaction',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='blogreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='blogreaction',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blog_reactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
