# Generated by Django 4.2.26 on 2026-05-21 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_blogblock_options_alter_blogcomment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, max_length=50, unique=True, verbose_name='status_name')),
                ('date_of_approval', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_approval', to=settings.AUTH_USER_MODEL)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approval', to='blog.blog')),
            ],
            options={
                'db_table': 'blog_approval',
                'ordering': ['date_of_approval'],
                'indexes': [models.Index(fields=['blog', 'date_of_approval'], name='blog_approv_blog_id_a0cccb_idx'), models.Index(fields=['blog', 'status'], name='blog_approv_blog_id_464212_idx'), models.Index(fields=['approver', 'blog'], name='blog_approv_approve_cabbe1_idx')],
            },
        ),
    ]
