# Generated by Django 4.2.26 on 2026-05-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogapproval',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, max_length=50, verbose_name='status_name'),
        ),
    ]
