# Generated by Django 4.2.26 on 2026-05-21 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_blogapproval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogapproval',
            name='approver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_approval', to=settings.AUTH_USER_MODEL),
        ),
    ]
