# Generated by Django 4.2.26 on 2026-05-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogapproval_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogapproval',
            name='date_of_rejection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogapproval',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
