# Generated by Django 4.2.26 on 2026-06-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogapproval_date_of_rejection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Total Views'),
        ),
    ]
