# Generated by Django 4.2.26 on 2026-04-01 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Fixed Price')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Discounted Price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Stock Quantity')),
                ('pid', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Product ID (PID)')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Calories (kcal)')),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Protein (g)')),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Carbohydrates (g)')),
                ('fibre', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Dietary Fibre (g)')),
                ('fats', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total Fats (g)')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional Info (JSON)')),
            ],
            options={
                'verbose_name': 'Product Profile',
                'verbose_name_plural': 'Product Profiles',
                'db_table': 'product_profile',
            },
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('status_name', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('LOW', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('PROCESSING', 'Processing'), ('REVIEW', 'Under Review'), ('REJECTED', 'Rejected')], max_length=30, unique=True, verbose_name='Status Name')),
            ],
            options={
                'verbose_name': 'Product Status',
                'verbose_name_plural': 'Product Statuses',
                'db_table': 'product_status',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('size_name', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], db_index=True, max_length=10, verbose_name='Size Name')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Weight')),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Millilitres'), ('l', 'Litres'), ('oz', 'Ounces'), ('lb', 'Pounds'), ('pcs', 'Pieces')], max_length=5, verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
                'db_table': 'product_size',
                'unique_together': {('size_name', 'weight', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('image', models.ImageField(upload_to='products/media/%Y/%m/', verbose_name='Image')),
                ('image_description', models.CharField(blank=True, max_length=500, verbose_name='Image Description')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Media',
                'verbose_name_plural': 'Product Media',
                'db_table': 'product_media',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productprofile', verbose_name='Nutritional Profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productsize', verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productstatus', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('tag_name', models.CharField(db_index=True, max_length=100, verbose_name='Tag Name')),
                ('tag_description', models.CharField(blank=True, max_length=255, verbose_name='Tag Description')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Product Tags',
                'db_table': 'product_tags',
                'indexes': [models.Index(fields=['tag_name'], name='product_tag_tag_nam_9e9dbb_idx')],
                'unique_together': {('product', 'tag_name')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['pid'], name='product_pid_82663d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_c4c985_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_categor_26b384_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='product_status__c36610_idx'),
        ),
    ]
