# Generated by Django 4.2.26 on 2026-05-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Trending'),
        ),
    ]
