# Generated by Django 4.2.26 on 2026-08-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cooking_instructions',
            field=models.TextField(blank=True, verbose_name='Instructions for Cooking'),
        ),
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.TextField(blank=True, verbose_name='Product Highlights'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Ingredients'),
        ),
    ]
