# Generated by Django 4.2.26 on 2026-08-27 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_product_cooking_instructions_product_highlights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1 to 5 star rating (Optional)', null=True)),
                ('content', models.TextField(verbose_name='Review Content')),
                ('is_approved', models.BooleanField(db_index=True, default=True, help_text='Set to False if you want manual moderation.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Comment',
                'verbose_name_plural': 'Product Comments',
                'db_table': 'product_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('image', models.ImageField(upload_to='products/reviews/%Y/%m/')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.productcomment')),
            ],
            options={
                'verbose_name': 'Product Comment Image',
                'verbose_name_plural': 'Product Comment Images',
                'db_table': 'product_comment_image',
            },
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='inventory.product')),
                ('user', models.ForeignKey(blank=True, help_text='Null if liked by an anonymous user.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Like',
                'verbose_name_plural': 'Product Likes',
                'db_table': 'product_like',
                'indexes': [models.Index(fields=['product', 'ip_address'], name='product_lik_product_3f7521_idx'), models.Index(fields=['product', 'user'], name='product_lik_product_7ec244_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['product', 'is_approved'], name='product_com_product_70cfe2_idx'),
        ),
    ]
