# Generated by Django 4.2.26 on 2026-09-03 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productcomment_productcommentimage_productlike_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShippingDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('weight', models.PositiveIntegerField(help_text='Shipping package weight in grams.', verbose_name='Package Weight (grams)')),
                ('length', models.PositiveIntegerField(help_text='Shipping package length in centimeters.', verbose_name='Package Length (cm)')),
                ('height', models.PositiveIntegerField(help_text='Shipping package height in centimeters.', verbose_name='Package Height (cm)')),
                ('width', models.PositiveIntegerField(help_text='Shipping package width in centimeters.', verbose_name='Package Width (cm)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_dimension', to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Shipping Dimension',
                'verbose_name_plural': 'Product Shipping Dimensions',
                'db_table': 'product_shipping_dimension',
            },
        ),
    ]
