# Generated by Django 4.2.26 on 2026-04-01 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
            ],
            options={
                'verbose_name': 'Inbox Entry',
                'verbose_name_plural': 'Inbox Entries',
                'db_table': 'inbox',
            },
        ),
        migrations.CreateModel(
            name='InboxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('type_name', models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received'), ('DRAFT', 'Draft')], max_length=20, unique=True, verbose_name='Inbox Type')),
            ],
            options={
                'verbose_name': 'Inbox Type',
                'verbose_name_plural': 'Inbox Types',
                'db_table': 'inbox_types',
            },
        ),
        migrations.CreateModel(
            name='MessageAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Sent At')),
            ],
            options={
                'verbose_name': 'Message Auth',
                'verbose_name_plural': 'Message Auths',
                'db_table': 'message_auth',
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('status_name', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('READ', 'Read')], max_length=20, unique=True, verbose_name='Status Name')),
            ],
            options={
                'verbose_name': 'Message Status',
                'verbose_name_plural': 'Message Statuses',
                'db_table': 'message_status',
            },
        ),
        migrations.CreateModel(
            name='MessageBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('text_content', models.TextField(blank=True, verbose_name='Text Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/images/%Y/%m/', verbose_name='Attached Image')),
                ('file', models.FileField(blank=True, null=True, upload_to='messages/files/%Y/%m/', verbose_name='Attached File')),
                ('message_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='messaging.messageauth', verbose_name='Message Auth')),
            ],
            options={
                'verbose_name': 'Message Body',
                'verbose_name_plural': 'Message Bodies',
                'db_table': 'message_body',
            },
        ),
        migrations.AddField(
            model_name='messageauth',
            name='message_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.messagestatus', verbose_name='Message Status'),
        ),
    ]
