# Generated by Django 4.2.26 on 2026-04-01 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messageauth',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Receiver'),
        ),
        migrations.AddField(
            model_name='messageauth',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbox_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_entries', to='messaging.inboxtype', verbose_name='Inbox Type'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='message_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_entries', to='messaging.messageauth', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_entries', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='messageauth',
            index=models.Index(fields=['sender'], name='message_aut_sender__4ffcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='messageauth',
            index=models.Index(fields=['receiver'], name='message_aut_receive_9a6d29_idx'),
        ),
        migrations.AddIndex(
            model_name='messageauth',
            index=models.Index(fields=['sent_at'], name='message_aut_sent_at_8b981d_idx'),
        ),
        migrations.AddIndex(
            model_name='messageauth',
            index=models.Index(fields=['message_status'], name='message_aut_message_ff0191_idx'),
        ),
        migrations.AddIndex(
            model_name='messageauth',
            index=models.Index(fields=['sender', 'receiver'], name='message_aut_sender__28041f_idx'),
        ),
        migrations.AddIndex(
            model_name='inbox',
            index=models.Index(fields=['user', 'inbox_type'], name='inbox_user_id_427076_idx'),
        ),
        migrations.AddIndex(
            model_name='inbox',
            index=models.Index(fields=['message_auth'], name='inbox_message_eca644_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inbox',
            unique_together={('user', 'message_auth', 'inbox_type')},
        ),
    ]
