# Generated by Django 4.2.26 on 2026-05-05 08:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Record ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created By IP')),
                ('updated_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Updated By IP')),
                ('response_url', models.URLField(verbose_name='Google Form URL')),
                ('email', models.EmailField(max_length=254, verbose_name="Responder's Email")),
                ('response_description', models.TextField(verbose_name='Response Description')),
            ],
            options={
                'verbose_name': 'Google Form Response',
                'verbose_name_plural': 'Google Form Responses',
                'db_table': 'google_form_responses',
            },
        ),
    ]
