# Generated by Django 4.2.26 on 2026-05-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_googleformresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleformresponse',
            name='mobile',
            field=models.CharField(default='N/A', max_length=20, verbose_name="Responder's Mobile Number"),
        ),
        migrations.AddField(
            model_name='googleformresponse',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255, verbose_name="Responder's Name"),
        ),
        migrations.AlterField(
            model_name='googleformresponse',
            name='email',
            field=models.EmailField(blank=True, default='N/A', max_length=254, null=True, verbose_name="Responder's Email"),
        ),
    ]
