# Generated by Django 4.2.26 on 2026-05-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_googleformresponse_mobile_googleformresponse_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleformresponse',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
