# Generated by Django 4.2.26 on 2026-05-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_googleformresponse_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleformresponse',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Responder address'),
        ),
    ]
