# Generated by Django 4.2.26 on 2026-04-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('inventory', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='user.session', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='processor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='shop.transactionprocessor', verbose_name='Processor'),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='sale_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shop.saleorder', verbose_name='Sale Order'),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='user.session', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='shop.transactionstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products', to='inventory.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='sale_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='shop.saleorder', verbose_name='Sale Order'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='shop.couponstatus', verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['order_date'], name='sale_order_order_d_b2899c_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['session'], name='sale_order_session_2c3dba_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertransaction',
            index=models.Index(fields=['sale_order'], name='order_trans_sale_or_55d522_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertransaction',
            index=models.Index(fields=['transaction_id'], name='order_trans_transac_1ff43f_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertransaction',
            index=models.Index(fields=['transaction_date'], name='order_trans_transac_e2fdbf_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertransaction',
            index=models.Index(fields=['status'], name='order_trans_status__29d8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertransaction',
            index=models.Index(fields=['processor'], name='order_trans_process_9c339b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertransaction',
            index=models.Index(fields=['sale_order', 'status'], name='order_trans_sale_or_350fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['sale_order'], name='order_produ_sale_or_cbdb60_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['product'], name='order_produ_product_382269_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['coupon_code'], name='coupon_coupon__afc38e_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['start_date', 'end_date'], name='coupon_start_d_eb7b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status'], name='coupon_status__7a38b4_idx'),
        ),
    ]
