# Generated by Django 4.2.26 on 2026-09-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='fulfillment_status',
            field=models.CharField(choices=[('UNFULFILLED', 'Unfulfilled (Queued)'), ('PROCESSING', 'Processing via Ekart'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='UNFULFILLED', max_length=20),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
