# Generated by Django 4.2.26 on 2026-09-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_saleorder_fulfillment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='consignee_alternate_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Consignee Alternate Phone'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='consignee_name',
            field=models.CharField(default='', max_length=255, verbose_name='Consignee Name'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='drop_city',
            field=models.CharField(default='', max_length=100, verbose_name='Drop City'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='drop_location',
            field=models.CharField(default='', max_length=500, verbose_name='Drop Location (Address, City, State, Pincode)'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='drop_pincode',
            field=models.CharField(default='', max_length=10, verbose_name='Drop Pincode'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='drop_state',
            field=models.CharField(default='', max_length=100, verbose_name='Drop State'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='pickup_location_alias',
            field=models.CharField(default='', max_length=100, verbose_name='Pickup Location Alias'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='preferred_dispatch_date',
            field=models.DateField(blank=True, null=True, verbose_name='Preferred Dispatch Date'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='service_type',
            field=models.CharField(choices=[('SURFACE', 'Surface'), ('EXPRESS', 'Express')], default='SURFACE', max_length=20, verbose_name='Service Type'),
        ),
    ]
