# Generated by Django 4.2.26 on 2026-09-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_saleorder_consignee_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='consignee_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Consignee Phone'),
        ),
    ]
