# Generated by Django 4.2.26 on 2026-09-21 09:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_saleorder_consignee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_auto_apply',
            field=models.BooleanField(default=False, help_text='If True, this coupon is automatically applied at checkout if no manual code is provided by the user.', verbose_name='Auto Apply'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum cart amount required to apply this coupon.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Minimum Order Value'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_auto_apply'], name='coupon_is_auto_cb0618_idx'),
        ),
    ]
