# Generated by Django 4.2.26 on 2026-09-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_order_products', to='shop.coupon', verbose_name='Applied Coupon'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (e.g., 18.00 for 18% GST)', max_digits=5, verbose_name='Tax Rate (%)'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Tax Amount'),
        ),
    ]
