# Generated by Django 4.2.26 on 2026-10-10 09:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderproduct_coupon_orderproduct_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Percentage Discount'), ('FLAT', 'Flat Amount Discount'), ('FREE_SHIPPING', 'Free Shipping')], max_length=20, verbose_name='Discount Type'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount Value'),
        ),
    ]
