# Generated by Django 4.2.26 on 2026-10-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_coupon_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(default='FLAT', max_length=50, verbose_name='Coupon Type'),
        ),
    ]
