# Generated by Django 4.2.26 on 2026-05-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('STAFF', 'Staff'), ('INVENTORY_MANAGER', 'Inventory Manager')], db_index=True, max_length=50, unique=True, verbose_name='Role Name'),
        ),
    ]
