# Generated by Django 4.2.26 on 2026-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='consignee_alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternate Phone'),
        ),
        migrations.AddField(
            model_name='address',
            name='consignee_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Consignee Name'),
        ),
        migrations.AddField(
            model_name='address',
            name='consignee_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Consignee Phone'),
        ),
    ]
